# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    public_dir: '%kernel.project_dir%/public/'
    file_dir: '%kernel.project_dir%/public/files/'
    frontend_urls:
        user_verification: '%env(USER_VERIFICATION_URL)%'
        new_user_email_verification: '%env(NEW_USER_EMAIL_VERIFICATION_URL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $commandBus: '@messenger.bus.command'
            $queryBus: '@messenger.bus.query'
            $eventBus: '@messenger.bus.event'

    _instanceof:
        App\Domain\Common\Message\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Domain\Common\Event\DomainEventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.event }

        App\Domain\Common\Message\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Application\Controller\:
        resource: '../src/Application/Controller/'
        tags: ['controller.service_arguments']

    #JWT
    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManagerInterface: '@lexik_jwt_authentication.jwt_manager'
    Gesdinet\JWTRefreshTokenBundle\EventListener\AttachRefreshTokenOnSuccessListener: '@gesdinet.jwtrefreshtoken.send_token'
    Gesdinet\JWTRefreshTokenBundle\Model\RefreshTokenManager: '@gesdinet.jwtrefreshtoken.refresh_token_manager'

    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class:  App\Application\Manager\RefreshTokenManager
        public: true
        arguments: [ '@gesdinet.jwtrefreshtoken.object_manager', '%gesdinet.jwtrefreshtoken.refresh_token.class%' ]

    # listeners
    App\Application\EventListener\Kernel\KernelExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Application\EventSubscriber\DomainEventsCollector:
        tags:
            - { name: doctrine.event_subscriber }

    App\Application\EventListener\Doctrine\TimestampsFiller:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    App\Application\EventListener\Kernel\RequestFormDataTransformer:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    # factory
    App\Application\Factory\Dto\Factory\AdvertisementAttachmentDtoFactory:
        arguments:
            $storageType: '%env(STORAGE_TYPE)%'

    # services
    App\Domain\Common\Service\FrontendUrlsGenerator:
        arguments:
            $frontendUrls: '%frontend_urls%'

    App\Infrastructure\Common\Service\EmailSender:
        arguments:
            $from: '%env(MAIL_FROM)%'

    App\Domain\File\Manager\FileManager:
        arguments:
            $strategies: !tagged app.strategy.content_storage

    App\Domain\Currency\Manager\ExchangeRatesManager:
        arguments:
            $strategies: !tagged app.strategy.exchange_rate_provider
    # strategies
    App\Infrastructure\File\Strategy\Storage\LocalFileStorage:
        arguments:
            $fileDir: '%file_dir%'
        tags:
            - { name: app.strategy.content_storage }

    App\Infrastructure\Currency\Strategy\ExchangeRatesProvider\PBExchangeRatesProvider:
        arguments:
            $apiUrl: '%env(PB_EXCHANGE_RATES_PROVIDER_URL)%'
        tags:
            - { name: app.strategy.exchange_rate_provider }
    # serializer
    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 5 }

    App\Application\Serializer\FileNormalizer:
        arguments:
            $publicDir: '%public_dir%'
        tags:
            - { name: serializer.normalizer, priority: 2 }

    App\Application\Serializer\UploadedFileDenormalizer:
        tags:
            - { name: serializer.normalizer, priority: 2 }