# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $commandBus: '@messenger.bus.command'
            $queryBus: '@messenger.bus.query'
            $eventBus: '@messenger.bus.event'

    _instanceof:
        App\Domain\Common\Message\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\App\Controller\:
        resource: '../src/App/Controller/'
        tags: ['controller.service_arguments']

    #JWT
    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManagerInterface: '@lexik_jwt_authentication.jwt_manager'
    Gesdinet\JWTRefreshTokenBundle\EventListener\AttachRefreshTokenOnSuccessListener: '@gesdinet.jwtrefreshtoken.send_token'
    Gesdinet\JWTRefreshTokenBundle\Model\RefreshTokenManager: '@gesdinet.jwtrefreshtoken.refresh_token_manager'

    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class:  App\App\Manager\RefreshTokenManager
        public: true
        arguments: [ '@gesdinet.jwtrefreshtoken.object_manager', '%gesdinet.jwtrefreshtoken.refresh_token.class%' ]

    # listeners
    App\App\EventListener\Kernel\KernelExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }